# Example config for generating and upscaling images with an INRF2D

num_samples: 1
batch_size: 1
# use_gpu: True
seed: 62
ignore_seed: True

# colormaps: [luv, hsv, lab]  # gray, hls
# For Zoom videos
#zoom_bounds: [1, .00000001] #[.0000001, 1000000] # 
#zoom_schedule: geometric # linear geometric, cosine, exp, sqrt, sigmoid, cbrt
# For Pan videos
#pan_bounds: [1, 100]
#pan_schedule: linear  # geometric, cosine, exp, sqrt, sigmoid, cbrt 
# For regenerating and augmenting images
regen_x_dim: 1000  # decrease to save memory
regen_y_dim: 1000
regen_z_dim: 1000
regen_c_dim: 4

splits: 100  # requires about 50GB of RAM for 100 splits
#save_video_from_volumes: True
regen_image_path: outputs/test_volume
output_dir: outputs/test_volume_rgba