# Example config for generating and upscaling images with an INRF2D

noise_dim: 16
noise_scale: 32
num_samples: 1
x_dim: 1024
y_dim: 1024
c_dim: 3
conv_feature_map_size: 64
activations: GELU # basic random nn.GELU
final_activation: !!null # sigmoid tanh
graph_topology: conv_fixed # conv_fixed, WS
batch_size: 1
# use_gpu: True
ws_graph_nodes: 64
weight_init: dip # normal uniform, dip, siren
input_file: neural_canvas/assets/logo.jpg
output_dir: outputs/fit_2d_example
tmp_dir: tmp/

seed: 62

discriminator_loss_weight: 0.0
l1_loss_weight: 1.0
l2_loss_weight: 0.0
ssim_loss_weight: 0.0
perceptual_loss_weight: 0.0
embedding_loss_weight: 0.0

lr: 0.001
weight_decay: 0.00005

num_epochs: 20
num_iters_per_epoch: 50
