# Example config for generating and upscaling images with an INRF2D

noise_dim: 8
noise_scale: 4
num_samples: 1
x_dim: 512
y_dim: 512
c_dim: 3
mlp_layer_width: 32
activations: random # fixed random nn.GELU
final_activation: tanh # sigmoid tanh !!null
graph_topology: mlp # conv, WS, mlp, simple
batch_size: 1
# use_gpu: True
ws_graph_nodes: 64
weight_init: normal # normal uniform, dip, siren
output_dir: outputs/test_gen
tmp_dir: tmp/

seed: 62
ignore_seed: True
# For generating randomized images
random_settings: True
# colormaps: [luv, hsv, lab]  # gray, hls