# Example config for generating and upscaling images with an INRF2D

noise_dim: 16
noise_scale: 32
num_samples: 2
x_dim: 256
y_dim: 256
c_dim: 3
mlp_layer_width: 32
activations: random # basic random nn.GELU
final_activation: !!null # sigmoid tanh
graph_topology: WS # conv_fixed, WS
batch_size: 1
# use_gpu: True
ws_graph_nodes: 64
weight_init: normal # normal uniform, dip, siren
output_dir: outputs/generate_2d_randomized5
tmp_dir: tmp/

seed: 62
ignore_seed: True
# For generating randomized images (best for getting lucky)
random_settings: True

# colormaps: [luv, hsv, lab]  # gray, hls