# Example config for generating and upscaling volumes with an INRF3D

noise_dim: 32
noise_scale: 4
num_samples: 1
x_dim: 256
y_dim: 256
z_dim: 256
c_dim: 3
mlp_layer_width: 32
activation_set: random # random, basic, nn.GELU
final_activation: tanh # sigmoid !!nulll tanh
graph_topology: WS # mlp_fixed conv_fixed, WS
batch_size: 1
# use_gpu: True
ws_graph_nodes: 10
weight_init: normal # normal uniform, dip, siren
output_dir: outputs/test_volume
tmp_dir: tmp/

seed: 62
ignore_seed: True
random_settings: True

# colormaps: [luv, hsv, lab]  # gray, hls
